#!/usr/bin/env python3
"""Turn a BDF bitmap font into a glyph table the driver can draw with.

The screen is the only channel left when the UART is not configured or is not
mapped, so the error paths need to draw text themselves. Drawing needs a font,
and a font is a table of small integers nobody wants to read or maintain by
hand, so it is generated once and the result is committed: the build then
needs nothing but what is in the tree.

    tests/tools/fontgen.py third_party/atarist-font/atarist-normal.bdf uefi/font.h

The source is https://github.com/ntwk/atarist-font: a BDF, which is a bitmap
written out as text, so the glyphs are read rather than rendered. That is the
reason this font was picked over an outline one: there is no question of
whether a renderer lands on the right pixels at the right size, because the
pixels are what is in the file.
"""
import re
import sys

# The printable range, which is what a message can be made of
FIRST = 32
LAST = 126

# What the drawer lays a line out with. Every glyph states its own size in its
# BBX line, and one that is not this is refused rather than guessed at
ROWS = 16
COLUMNS = 8


def glyphsOf(text):
    """Every glyph in the file, as {code: [row, ...]}."""
    glyphs = {}

    for block in re.findall(r"^STARTCHAR .*?^ENDCHAR$", text, re.M | re.S):
        code = re.search(r"^ENCODING (-?\d+)$", block, re.M)
        bbx = re.search(r"^BBX (\d+) (\d+) (-?\d+) (-?\d+)$", block, re.M)
        bitmap = re.search(r"^BITMAP$(.*)", block, re.M | re.S)
        if code is None or bbx is None or bitmap is None:
            continue
        width, rows, xOffset, yOffset = (int(v) for v in bbx.groups())
        if width != COLUMNS or rows != ROWS or xOffset != 0 or yOffset != -2:
            raise SystemExit("a glyph is %dx%d at (%d,%d), and this font is "
                             "%dx%d at (0,-2)"
                             % (width, rows, xOffset, yOffset, COLUMNS, ROWS))
        cells = []
        for line in bitmap.group(1).strip().split("\n"):
            # The block ends with ENDCHAR, which is not a row of the glyph
            if line == "ENDCHAR":
                break
            if len(line) != COLUMNS // 4:
                raise SystemExit("a row is %r, and a row of this font is %d hex "
                                 "digits" % (line, COLUMNS // 4))
            cells.append(int(line, 16))
        if len(cells) != ROWS:
            raise SystemExit("a glyph has %d rows, and this font has %d"
                             % (len(cells), ROWS))
        glyphs[int(code.group(1))] = cells
    return glyphs


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: fontgen.py <font.bdf> <out.h>")
    source, target = sys.argv[1], sys.argv[2]
    glyphs = glyphsOf(open(source, encoding="latin1").read())

    table = []
    for code in range(FIRST, LAST + 1):
        if code not in glyphs:
            raise SystemExit("the font has no glyph for 0x%02x" % code)
        rows = glyphs[code]
        if not any(rows) and code != FIRST:
            raise SystemExit("%r is blank" % chr(code))
        table.append((code, rows))

    out = []
    out.append("/*")
    out.append(" * The glyphs the screen drawer uses, for ASCII %d to %d" % (FIRST, LAST))
    out.append(" *")
    out.append(" * Generated by tests/tools/fontgen.py from the font at")
    out.append(" * https://github.com/ntwk/atarist-font, which is %d by %d. Committed" % (COLUMNS, ROWS))
    out.append(" * rather than generated at build time so that a build needs nothing but")
    out.append(" * this tree")
    out.append(" *")
    out.append(" * One byte per row, most significant bit on the left, %d rows a glyph," % ROWS)
    out.append(" * the first row at the top. This file is not meant to be edited")
    out.append(" */")
    out.append("")
    out.append("#ifndef US_FONT_H")
    out.append("#define US_FONT_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("#define US_FONT_FIRST %d" % FIRST)
    out.append("#define US_FONT_LAST %d" % LAST)
    out.append("#define US_FONT_WIDTH %d" % COLUMNS)
    out.append("#define US_FONT_HEIGHT %d" % ROWS)
    out.append("")
    out.append("static const uint8_t kFont[US_FONT_LAST - US_FONT_FIRST + 1][US_FONT_HEIGHT] = {")
    for code, rows in table:
        cells = ", ".join("0x%02x" % value for value in rows)
        shown = "space" if code == FIRST else chr(code)
        out.append("    { %s }, /* %s */" % (cells, shown))
    out.append("};")
    out.append("")
    out.append("#endif")
    with open(target, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s: %d glyphs, %dx%d"
          % (target, len(table), COLUMNS, ROWS))


if __name__ == "__main__":
    main()
