#!/usr/bin/env python3
"""Turn a console font into a glyph table the driver can draw with.

The screen is the only channel left when the UART is not configured or is not
mapped, so the error paths need to draw text themselves. Drawing needs a font
and a font is 1.5 kilobytes of data nobody wants to read or maintain by hand,
so it is generated once from a console font the system already has and the
result is committed: the build then needs nothing but what is in the tree.

    tests/tools/fontgen.py /usr/share/kbd/consolefonts/cp850-8x16.psfu.gz \
        uefi/src/font8x16.h

The source font is a PSF2 file, one byte per row for an eight wide glyph, most
significant bit on the left, and the first ninety-five glyphs are ASCII from
the space to the tilde.
"""
import gzip
import struct
import sys

PSF1_MAGIC = b"\x36\x04"
# The magic is written in the file's own order, which is the reverse of the
# little endian reading of it.
PSF2_MAGIC = b"\x72\xb5\x4a\x86"


def readPsf1(data):
    """PSF1: a four byte header, then 256 or 512 glyphs of equal size."""
    mode = data[2]
    charSize = data[3]
    if mode & 0x01:
        charSize *= 2
    if mode & 0x02:
        # A unicode table follows the glyphs, which does not move them.
        pass
    height = charSize
    if height not in (8, 14, 16):
        raise SystemExit("PSF1 glyphs are %d bytes, which is not a height this knows" % height)
    return 4, charSize, height


def readPsf2(data):
    if data[:4] != PSF2_MAGIC:
        raise SystemExit("not a PSF2 font")
    version, headerSize, flags, length, charSize, height, width = struct.unpack_from(
        "<IIIIIII", data, 4)
    if width != 8:
        raise SystemExit("font is %d wide, and the drawer wants eight" % width)
    if length < 127:
        raise SystemExit("font holds %d glyphs, fewer than ASCII needs" % length)
    return headerSize, charSize, height


def main():
    source, target = sys.argv[1], sys.argv[2]
    if source.endswith(".gz"):
        with gzip.open(source, "rb") as f:
            data = f.read()
    else:
        with open(source, "rb") as f:
            data = f.read()

    if data[:2] == PSF1_MAGIC:
        headerSize, charSize, height = readPsf1(data)
    else:
        headerSize, charSize, height = readPsf2(data)
    if height != 16:
        raise SystemExit("%s is %d high, and the drawer wants sixteen" % (source, height))

    out = []
    out.append("/*")
    out.append(" * The glyphs the screen drawer uses, for ASCII 32 to 126.")
    out.append(" *")
    out.append(" * Generated by tests/tools/fontgen.py from %s," % source.split("/")[-1])
    out.append(" * which is a console font the system already had. Committed rather than")
    out.append(" * generated at build time so that a build needs nothing but this tree.")
    out.append(" *")
    out.append(" * One byte per row, most significant bit on the left, sixteen rows a")
    out.append(" * glyph, the first row at the top. This file is not meant to be edited.")
    out.append(" */")
    out.append("")
    out.append("#ifndef US_FONT8X16_H")
    out.append("#define US_FONT8X16_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("#define US_FONT_FIRST 32")
    out.append("#define US_FONT_LAST 126")
    out.append("#define US_FONT_WIDTH 8")
    out.append("#define US_FONT_HEIGHT 16")
    out.append("")
    out.append("static const uint8_t kFont8x16[US_FONT_LAST - US_FONT_FIRST + 1][US_FONT_HEIGHT] = {")
    for code in range(32, 127):
        glyph = data[headerSize + code * charSize:headerSize + (code + 1) * charSize]
        rows = ", ".join("0x%02x" % b for b in glyph[:16])
        shown = chr(code) if code != 32 else "space"
        out.append("    { %s }, /* %s */" % (rows, shown))
    out.append("};")
    out.append("")
    out.append("#endif")
    with open(target, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s: %d glyphs, %d bytes each" % (target, 95, 16))


if __name__ == "__main__":
    main()
