/*
 * layoutgen - turn the payload's structures into assembly constants.
 *
 * The frame is described once, in C, and both the handler and the assembly
 * entry have to agree on it. Keeping a second copy in the assembly is how the
 * two drift apart, and the failure is silent: the entry stores a register at
 * an offset the handler does not read.
 *
 * So the offsets are printed from the structure that defines them. This runs
 * on the host, against the same header the payload is built with.
 *
 * Usage: layoutgen <output-file>
 */

#include <stdio.h>
#include <stddef.h>

#include "payload/payload.h"

static int emitFrame(FILE *f) {
    fprintf(f, "/* Generated by tests/tools/layoutgen.c. Do not edit. */\n");
    fprintf(f, "\n");
    fprintf(f, "#define US_FRAME_SIZE %zu\n", sizeof(UsFrame));
    fprintf(f, "#define US_FRAME_STRIDE %zu\n", sizeof(UsFrame));

    for (int i = 0; i < 31; i++) {
        fprintf(f, "#define US_FRAME_X%d %zu\n", i, offsetof(UsFrame, x) + i * sizeof(uint64_t));
    }
    fprintf(f, "#define US_FRAME_SP %zu\n", offsetof(UsFrame, sp));
    fprintf(f, "#define US_FRAME_ELR %zu\n", offsetof(UsFrame, elr));
    fprintf(f, "#define US_FRAME_SPSR %zu\n", offsetof(UsFrame, spsr));
    fprintf(f, "#define US_FRAME_ESR %zu\n", offsetof(UsFrame, esr));
    fprintf(f, "#define US_FRAME_FAR %zu\n", offsetof(UsFrame, far));

    fprintf(f, "\n");
    fprintf(f, "#define US_CONFIG_UART %zu\n", offsetof(UsPayloadConfig, uartBase));
    fprintf(f, "#define US_CONFIG_STACK_TOP %zu\n", offsetof(UsPayloadConfig, stackTop));
    fprintf(f, "#define US_CONFIG_STACK_STRIDE %zu\n", sizeof(uint64_t));
    fprintf(f, "#define US_CONFIG_MAX_CPUS %zu\n",
            sizeof(((UsPayloadConfig *)0)->stackTop) / sizeof(uint64_t));
    fprintf(f, "#define US_CONFIG_SELF_VA %zu\n", offsetof(UsPayloadConfig, selfVa));
    fprintf(f, "#define US_CONFIG_FORWARD %zu\n", offsetof(UsPayloadConfig, forwardTarget));
    fprintf(f, "#define US_CONFIG_SIZE %zu\n", sizeof(UsPayloadConfig));

    return 0;
}

int main(int argc, char **argv) {
    FILE *f;

    if (argc != 2) {
        fprintf(stderr, "usage: %s <output-file>\n", argv[0]);
        return 2;
    }
    f = fopen(argv[1], "w");
    if (f == NULL) {
        fprintf(stderr, "cannot write %s\n", argv[1]);
        return 2;
    }
    if (emitFrame(f) != 0 || fclose(f) != 0) {
        fprintf(stderr, "cannot write %s\n", argv[1]);
        return 2;
    }
    return 0;
}
