/*
 * layoutgen - turn the payload's structures into assembly constants
 *
 * The frame is described once, in C, and both the handler and the assembly
 * entry have to agree on it. Keeping a second copy in the assembly is how the
 * two drift apart, and the failure is silent: the entry stores a register at
 * an offset the handler does not read
 *
 * So the offsets are printed from the structure that defines them. This runs
 * on the host, against the same header the payload is built with
 *
 * Usage: layoutgen <output-file>
 */

#include <stdio.h>
#include <stddef.h>

#include "core/thunk.h"
#include "payload/payload.h"

static int emitFrame(FILE *f) {
    fprintf(f, "/* Generated by tests/tools/layoutgen.c. Do not edit. */\n");
    fprintf(f, "\n");
    fprintf(f, "#define US_FRAME_SIZE %zu\n", sizeof(UsFrame));
    fprintf(f, "#define US_FRAME_STRIDE %zu\n", sizeof(UsFrame));

    for (int i = 0; i < 31; i++) {
        fprintf(f, "#define US_FRAME_X%d %zu\n", i, offsetof(UsFrame, x) + i * sizeof(uint64_t));
    }
    fprintf(f, "#define US_FRAME_SP %zu\n", offsetof(UsFrame, sp));
    fprintf(f, "#define US_FRAME_ELR %zu\n", offsetof(UsFrame, elr));
    fprintf(f, "#define US_FRAME_SPSR %zu\n", offsetof(UsFrame, spsr));
    fprintf(f, "#define US_FRAME_ESR %zu\n", offsetof(UsFrame, esr));
    fprintf(f, "#define US_FRAME_FAR %zu\n", offsetof(UsFrame, far));
    /* Where the entry branches instead of returning, when the payload hands
     * the exception to the kernel's own handler */
    fprintf(f, "#define US_FRAME_LANDING %zu\n", offsetof(UsFrame, landing));

    fprintf(f, "\n");
    fprintf(f, "#define US_CONFIG_UART %zu\n", offsetof(UsPayloadConfig, uartBase));
    fprintf(f, "#define US_CONFIG_STACK_TOP %zu\n", offsetof(UsPayloadConfig, stackTop));
    fprintf(f, "#define US_CONFIG_STACK_STRIDE %zu\n", sizeof(uint64_t));
    fprintf(f, "#define US_CONFIG_MAX_CPUS %zu\n",
            sizeof(((UsPayloadConfig *)0)->stackTop) / sizeof(uint64_t));
    fprintf(f, "#define US_CONFIG_SELF_VA %zu\n", offsetof(UsPayloadConfig, selfVa));
    fprintf(f, "#define US_CONFIG_POOL %zu\n", offsetof(UsPayloadConfig, poolBase));
    fprintf(f, "#define US_CONFIG_QUIET %zu\n", offsetof(UsPayloadConfig, quiet));
    fprintf(f, "#define US_CONFIG_CPU_COUNT %zu\n", offsetof(UsPayloadConfig, cpuCount));
    fprintf(f, "#define US_CONFIG_CPUS %zu\n", offsetof(UsPayloadConfig, cpus));
    fprintf(f, "#define US_CONFIG_SIZE %zu\n", sizeof(UsPayloadConfig));
    fprintf(f, "#define US_CONFIG_HIGH_VA %zu\n", offsetof(UsPayloadConfig, highVa));
    fprintf(f, "#define US_CONFIG_HIGH_POOL_VA %zu\n", offsetof(UsPayloadConfig, highPoolVa));
    fprintf(f, "#define US_CONFIG_STUB_COUNT %zu\n", offsetof(UsPayloadConfig, stubCount));
    fprintf(f, "#define US_CONFIG_STUBS %zu\n", offsetof(UsPayloadConfig, stubs));
    fprintf(f, "#define US_STUB_STRIDE %zu\n", sizeof(UsPayloadStub));
    fprintf(f, "#define US_STUB_ADDRESS %zu\n", offsetof(UsPayloadStub, address));
    fprintf(f, "#define US_STUB_TABLE %zu\n", offsetof(UsPayloadStub, tableAddress));
    fprintf(f, "#define US_STUB_IMAGE %zu\n", offsetof(UsPayloadStub, imageAddress));
    fprintf(f, "#define US_STUB_TABLE_PA %zu\n", offsetof(UsPayloadStub, tablePa));
    fprintf(f, "#define US_STUB_ADDRESS_PA %zu\n", offsetof(UsPayloadStub, addressPa));
    fprintf(f, "#define US_STUB_TARGET %zu\n", offsetof(UsPayloadStub, targetIndex));
    fprintf(f, "#define US_STUB_PUBLISHED %zu\n", offsetof(UsPayloadStub, published));

    /* One processor entry, as the entry's lookup walks it */
    fprintf(f, "#define US_CPU_STRIDE %zu\n", sizeof(UsPayloadCpu));
    fprintf(f, "#define US_CPU_INDEX %zu\n", offsetof(UsPayloadCpu, index));

    /*
     * The mask the entry applies to MPIDR_EL1. Taken from the header rather
     * than written into the assembly, where it was a second copy: the one in
     * C is a list of wanted fields, and that word is not a logical immediate
     * the instruction can carry, so the assembly had a different one that
     * happened to work
     */
    fprintf(f, "#define US_MPIDR_MASK 0x%llx\n",
            (unsigned long long)US_MPIDR_AFFINITY_MASK_LOGICAL);

    /* The entry asks whether the stack pointer it was given is already inside
     * this CPU's own stack, which is how a fault inside the payload is told
     * from an exception of the interrupted code's */
    fprintf(f, "#define US_STACK_SIZE %u\n", US_STACK_SIZE);

    /* The room the entry takes to give the handler's registers back when the
     * handler answers that the payload is to carry on where it was */
    fprintf(f, "#define US_FAULT_SPILL_BYTES %u\n", US_FAULT_SPILL_BYTES);

    return 0;
}

int main(int argc, char **argv) {
    FILE *f;

    if (argc != 2) {
        fprintf(stderr, "usage: %s <output-file>\n", argv[0]);
        return 2;
    }
    f = fopen(argv[1], "w");
    if (f == NULL) {
        fprintf(stderr, "cannot write %s\n", argv[1]);
        return 2;
    }
    if (emitFrame(f) != 0 || fclose(f) != 0) {
        fprintf(stderr, "cannot write %s\n", argv[1]);
        return 2;
    }
    return 0;
}
